"""ingestion runs tasks provenance author profiles

Revision ID: 2d67f5495269
Revises: b1c2d3e4f5a6
Create Date: 2026-07-01 22:13:56.563070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2d67f5495269'
down_revision: Union[str, None] = 'b1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author_profiles',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('handle', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('follower_count', sa.Integer(), nullable=True),
    sa.Column('profile_url', sa.String(), nullable=True),
    sa.Column('last_refreshed', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'handle', name='uq_author_profiles_platform_handle')
    )
    op.create_table('ingestion_runs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('politician_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('window_end', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('credit_budget', sa.Float(), nullable=True),
    sa.Column('credits_spent', sa.Float(), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['politician_id'], ['politicians.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_tasks',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('run_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('connector', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('page_cursor', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('credits_spent', sa.Float(), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['ingestion_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_tasks_run_id'), 'ingestion_tasks', ['run_id'], unique=False)
    op.add_column('politicians', sa.Column('titles', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('politicians', sa.Column('swahili_terms', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('politicians', sa.Column('tracked_hashtags', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('raw_mentions', sa.Column('run_id', sa.UUID(as_uuid=False), nullable=True))
    op.add_column('raw_mentions', sa.Column('source_endpoint', sa.String(), nullable=True))
    op.add_column('raw_mentions', sa.Column('source_url', sa.String(), nullable=True))
    op.add_column('raw_mentions', sa.Column('fetched_at', sa.DateTime(), nullable=True))
    op.add_column('raw_mentions', sa.Column('language', sa.String(), nullable=True))
    op.add_column('raw_mentions', sa.Column('author_platform_id', sa.String(), nullable=True))
    op.add_column('raw_mentions', sa.Column('link_checked', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_raw_mentions_run_id', 'raw_mentions', 'ingestion_runs', ['run_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_raw_mentions_run_id', 'raw_mentions', type_='foreignkey')
    op.drop_column('raw_mentions', 'link_checked')
    op.drop_column('raw_mentions', 'author_platform_id')
    op.drop_column('raw_mentions', 'language')
    op.drop_column('raw_mentions', 'fetched_at')
    op.drop_column('raw_mentions', 'source_url')
    op.drop_column('raw_mentions', 'source_endpoint')
    op.drop_column('raw_mentions', 'run_id')
    op.drop_column('politicians', 'tracked_hashtags')
    op.drop_column('politicians', 'swahili_terms')
    op.drop_column('politicians', 'titles')
    op.drop_index(op.f('ix_ingestion_tasks_run_id'), table_name='ingestion_tasks')
    op.drop_table('ingestion_tasks')
    op.drop_table('ingestion_runs')
    op.drop_table('author_profiles')
    # ### end Alembic commands ###
