"""due-diligence core: documents, events, knowledge graph, credibility, claims, snapshots

Revision ID: 30383dab9b6f
Revises: f6a7b8c9d0e1
Create Date: 2026-07-30 07:43:24.716045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30383dab9b6f'
down_revision: Union[str, None] = 'f6a7b8c9d0e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_credibility',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('corroboration_rate', sa.Float(), nullable=True),
    sa.Column('observations', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_credibility_key'), 'source_credibility', ['key'], unique=True)
    op.create_table('entity_relationships',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('politician_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('source_entity_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('target_entity_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('rel_type', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence_count', sa.Integer(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['politician_id'], ['politicians.id'], ),
    sa.ForeignKeyConstraint(['source_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_entity_id', 'target_entity_id', 'rel_type', name='uq_entity_rel')
    )
    op.create_index(op.f('ix_entity_relationships_politician_id'), 'entity_relationships', ['politician_id'], unique=False)
    op.create_index(op.f('ix_entity_relationships_rel_type'), 'entity_relationships', ['rel_type'], unique=False)
    op.create_index(op.f('ix_entity_relationships_source_entity_id'), 'entity_relationships', ['source_entity_id'], unique=False)
    op.create_index(op.f('ix_entity_relationships_target_entity_id'), 'entity_relationships', ['target_entity_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('politician_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=True),
    sa.Column('occurred_precision', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('corroboration_count', sa.Integer(), nullable=True),
    sa.Column('independent_domains', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('significance', sa.Float(), nullable=True),
    sa.Column('dedupe_key', sa.String(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['politician_id'], ['politicians.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_dedupe_key'), 'events', ['dedupe_key'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_occurred_at'), 'events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_events_politician_id'), 'events', ['politician_id'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('politician_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('report_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('claim_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence_count', sa.Integer(), nullable=True),
    sa.Column('independent_sources', sa.Integer(), nullable=True),
    sa.Column('verifier_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['politician_id'], ['politicians.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['intelligence_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_politician_id'), 'claims', ['politician_id'], unique=False)
    op.create_index(op.f('ix_claims_report_id'), 'claims', ['report_id'], unique=False)
    op.create_index(op.f('ix_claims_status'), 'claims', ['status'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('politician_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('source_tier', sa.String(), nullable=True),
    sa.Column('doc_type', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('relevance_verdict', sa.String(), nullable=True),
    sa.Column('relevance_reason', sa.Text(), nullable=True),
    sa.Column('processed_stages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('run_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['politician_id'], ['politicians.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['ingestion_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('politician_id', 'content_hash', name='uq_document_subject_hash')
    )
    op.create_index(op.f('ix_documents_content_hash'), 'documents', ['content_hash'], unique=False)
    op.create_index(op.f('ix_documents_domain'), 'documents', ['domain'], unique=False)
    op.create_index(op.f('ix_documents_politician_id'), 'documents', ['politician_id'], unique=False)
    op.create_index(op.f('ix_documents_published_at'), 'documents', ['published_at'], unique=False)
    op.create_index(op.f('ix_documents_relevance_verdict'), 'documents', ['relevance_verdict'], unique=False)
    op.create_index(op.f('ix_documents_source'), 'documents', ['source'], unique=False)
    op.create_table('snapshots',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('politician_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('run_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('taken_at', sa.DateTime(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('entity_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('narrative_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('delta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['politician_id'], ['politicians.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['ingestion_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snapshots_politician_id'), 'snapshots', ['politician_id'], unique=False)
    op.create_index(op.f('ix_snapshots_taken_at'), 'snapshots', ['taken_at'], unique=False)
    op.create_table('claim_evidence',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('claim_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('mention_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('document_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('quote', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('stance', sa.String(), nullable=True),
    sa.Column('credibility', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['mention_id'], ['raw_mentions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_evidence_claim_id'), 'claim_evidence', ['claim_id'], unique=False)
    op.create_table('event_evidence',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('event_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('mention_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('document_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('quote', sa.Text(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['mention_id'], ['raw_mentions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'mention_id', 'document_id', name='uq_event_evidence')
    )
    op.create_index(op.f('ix_event_evidence_event_id'), 'event_evidence', ['event_id'], unique=False)
    op.create_table('mention_classifications',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('mention_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('document_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('subtopics', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('content_kind', sa.String(), nullable=True),
    sa.Column('is_substantive', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['mention_id'], ['raw_mentions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mention_classifications_document_id'), 'mention_classifications', ['document_id'], unique=False)
    op.create_index(op.f('ix_mention_classifications_mention_id'), 'mention_classifications', ['mention_id'], unique=False)
    op.create_index(op.f('ix_mention_classifications_topic'), 'mention_classifications', ['topic'], unique=False)
    op.add_column('entities', sa.Column('aliases', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('entities', sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('entities', sa.Column('mention_count', sa.Integer(), nullable=True))
    op.add_column('entities', sa.Column('first_seen', sa.DateTime(), nullable=True))
    op.add_column('entities', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###

    # Full-text retrieval over the evidence corpus. The GIN index is what makes
    # "find the one paragraph that mentions this 1992 contract" fast enough to
    # run per-question during analysis. search_vector is maintained by a trigger
    # so it can never drift from the stored text.
    op.execute("CREATE INDEX IF NOT EXISTS ix_documents_search_vector ON documents USING GIN (search_vector)")
    op.execute(
        """
        CREATE OR REPLACE FUNCTION documents_search_vector_update() RETURNS trigger AS $$
        BEGIN
          NEW.search_vector :=
            setweight(to_tsvector('english', coalesce(NEW.title, '')), 'A') ||
            setweight(to_tsvector('english', coalesce(NEW.body, '')), 'B');
          RETURN NEW;
        END
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER documents_search_vector_trigger
        BEFORE INSERT OR UPDATE OF title, body ON documents
        FOR EACH ROW EXECUTE FUNCTION documents_search_vector_update();
        """
    )
    # Trigram index for fuzzy title/entity matching during event de-duplication.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE INDEX IF NOT EXISTS ix_events_title_trgm ON events USING GIN (title gin_trgm_ops)")


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_events_title_trgm")
    op.execute("DROP TRIGGER IF EXISTS documents_search_vector_trigger ON documents")
    op.execute("DROP FUNCTION IF EXISTS documents_search_vector_update()")
    op.execute("DROP INDEX IF EXISTS ix_documents_search_vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entities', 'last_seen')
    op.drop_column('entities', 'first_seen')
    op.drop_column('entities', 'mention_count')
    op.drop_column('entities', 'attributes')
    op.drop_column('entities', 'aliases')
    op.drop_index(op.f('ix_mention_classifications_topic'), table_name='mention_classifications')
    op.drop_index(op.f('ix_mention_classifications_mention_id'), table_name='mention_classifications')
    op.drop_index(op.f('ix_mention_classifications_document_id'), table_name='mention_classifications')
    op.drop_table('mention_classifications')
    op.drop_index(op.f('ix_event_evidence_event_id'), table_name='event_evidence')
    op.drop_table('event_evidence')
    op.drop_index(op.f('ix_claim_evidence_claim_id'), table_name='claim_evidence')
    op.drop_table('claim_evidence')
    op.drop_index(op.f('ix_snapshots_taken_at'), table_name='snapshots')
    op.drop_index(op.f('ix_snapshots_politician_id'), table_name='snapshots')
    op.drop_table('snapshots')
    op.drop_index(op.f('ix_documents_source'), table_name='documents')
    op.drop_index(op.f('ix_documents_relevance_verdict'), table_name='documents')
    op.drop_index(op.f('ix_documents_published_at'), table_name='documents')
    op.drop_index(op.f('ix_documents_politician_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_domain'), table_name='documents')
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_claims_status'), table_name='claims')
    op.drop_index(op.f('ix_claims_report_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_politician_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_events_politician_id'), table_name='events')
    op.drop_index(op.f('ix_events_occurred_at'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_dedupe_key'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_entity_relationships_target_entity_id'), table_name='entity_relationships')
    op.drop_index(op.f('ix_entity_relationships_source_entity_id'), table_name='entity_relationships')
    op.drop_index(op.f('ix_entity_relationships_rel_type'), table_name='entity_relationships')
    op.drop_index(op.f('ix_entity_relationships_politician_id'), table_name='entity_relationships')
    op.drop_table('entity_relationships')
    op.drop_index(op.f('ix_source_credibility_key'), table_name='source_credibility')
    op.drop_table('source_credibility')
    # ### end Alembic commands ###
