"""add social_handles to politicians

Revision ID: 599ec097724c
Revises: aa2028c7dbfa
Create Date: 2026-06-24 16:17:30.908501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '599ec097724c'
down_revision: Union[str, None] = 'aa2028c7dbfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('politicians', sa.Column('social_handles', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('politicians', 'social_handles')
    # ### end Alembic commands ###
