"""run progress — durable section-by-section delivery

Sections were streamed into process memory only, so a run that outlived the
poll window — or a reload, a closed tab, or a restarted free instance — threw
away everything already produced. The work had happened; there was nowhere to
look for it.

One row per (subject, kind), upserted as each section lands. Deliberately NOT
stored in `intelligence_reports`: a half-built payload filed there would be
picked up by `compute_deltas` as "the previous report" and silently corrupt
every subsequent report-over-report comparison.

Written by hand rather than autogenerated. Autogenerate cannot see the
expression/GIN indexes created with raw DDL in 30383dab9b6f and proposes
dropping them, which would disable full-text evidence retrieval — the thing the
due-diligence promise rests on.

Revision ID: a1b2c3d4e5f6
Revises: c3da26bd08ae
Create Date: 2026-08-19

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "a1b2c3d4e5f6"
down_revision: Union[str, None] = "c3da26bd08ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "run_progress",
        sa.Column("id", postgresql.UUID(as_uuid=False), nullable=False),
        sa.Column("subject_key", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("job_id", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False, server_default="running"),
        sa.Column("stage", sa.Text(), nullable=True),
        sa.Column("sections_ready", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("subject_key", "kind", name="uq_run_progress_subject_kind"),
    )
    op.create_index("ix_run_progress_updated_at", "run_progress", ["updated_at"])


def downgrade() -> None:
    op.drop_index("ix_run_progress_updated_at", table_name="run_progress")
    op.drop_table("run_progress")
