"""initial schema

Revision ID: aa2028c7dbfa
Revises: 
Create Date: 2026-06-22 22:04:08.995830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa2028c7dbfa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('politicians',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('aliases', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('keywords', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intelligence_reports',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('politician_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('window_end', sa.DateTime(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['politician_id'], ['politicians.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('narratives',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('politician_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['politician_id'], ['politicians.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_mentions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('politician_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('author_handle', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=False),
    sa.Column('engagement_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('is_spam', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['politician_id'], ['politicians.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_mentions_content_hash'), 'raw_mentions', ['content_hash'], unique=False)
    op.create_table('mention_entities',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('mention_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('entity_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('match_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['mention_id'], ['raw_mentions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mention_narratives',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('mention_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('narrative_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['mention_id'], ['raw_mentions.id'], ),
    sa.ForeignKeyConstraint(['narrative_id'], ['narratives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mention_sentiment',
    sa.Column('mention_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('sentiment', sa.String(), nullable=False),
    sa.Column('intensity', sa.Integer(), nullable=False),
    sa.Column('context_tag', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['mention_id'], ['raw_mentions.id'], ),
    sa.PrimaryKeyConstraint('mention_id')
    )
    op.create_table('narrative_metrics',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('narrative_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('window_end', sa.DateTime(), nullable=False),
    sa.Column('strength_score', sa.Float(), nullable=True),
    sa.Column('growth_rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['narrative_id'], ['narratives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('narrative_metrics')
    op.drop_table('mention_sentiment')
    op.drop_table('mention_narratives')
    op.drop_table('mention_entities')
    op.drop_index(op.f('ix_raw_mentions_content_hash'), table_name='raw_mentions')
    op.drop_table('raw_mentions')
    op.drop_table('narratives')
    op.drop_table('intelligence_reports')
    op.drop_table('politicians')
    op.drop_table('entities')
    # ### end Alembic commands ###
